# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.8.1
_src_path: gh:algorandfoundation/algokit-python-template
author_email: testbest405@gmail.com
author_name: Admin
contract_name: hello_world
deployment_language: python
preset_name: production
project_name: credchain-contracts

